name: Go

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        clean: true
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Fetch dependencies
      run: go get -d
    - name: Build
      run: go build
    - name: Write secrets
      - run: 'echo "$FIREBASE_WEB" > firebase_web.json'
      shell: bash
      env:
        FIREBASE_WEB: ${{secrets.FIREBASE_WEB}}
    - name: Kill old
      run: kill $(lsof -t -i:8080)
    - name: Run
      run: RUNNER_TRACKING_ID="" && ./nikki -p 8080 -db ${{ secrets.DATABASE_URL }} &