name: Go

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    environment: aws_prototype
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        clean: false
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: secret test
        run: echo $"TEST"
        env: 
          TEST: ${{ secrets.TEST }}
    - name: Fetch dependencies
      run: go get -d
    - name: Build
      run: go build
    - name: Kill old
      run: kill $(lsof -t -i:8080)
    - name: Run
      run: RUNNER_TRACKING_ID="" && ./nikki -p 8080 -db ${{ secrets.DATABASE_URL }} &